//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SampleMicroserviceApp.Identity.Domain.Resources.ExceptionMessages {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ExceptionStrings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ExceptionStrings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SampleMicroserviceApp.Identity.Domain.Resources.ExceptionMessages.ExceptionStrings", typeof(ExceptionStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to خطایی در گردش کار اتفاق افتاد. با پشتیبانی تماس بگیرید.
        /// </summary>
        public static string DoActionCommand_ErrorHappenedInWorkflowSystem {
            get {
                return ResourceManager.GetString("DoActionCommand_ErrorHappenedInWorkflowSystem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to هیچ درخواستی یافت نشد.
        /// </summary>
        public static string DoActionCommand_NoCrewRequestWasFound {
            get {
                return ResourceManager.GetString("DoActionCommand_NoCrewRequestWasFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مرحله گردش کار جاری یافت نشد.
        /// </summary>
        public static string DoActionCommand_NoFlowWasFoundForRequest {
            get {
                return ResourceManager.GetString("DoActionCommand_NoFlowWasFoundForRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to کاربر ثبت کننده درخواست در سیستم راهکاران منابع انسانی وجود ندارد.
        /// </summary>
        public static string DoActionCommand_UserNotFound {
            get {
                return ResourceManager.GetString("DoActionCommand_UserNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to هیچ مرحله‌ی گردش کاری برای این درخواست وجود ندارد.
        /// </summary>
        public static string GetPossibleActionsQuery_NoFlowWasFoundForThisRequest {
            get {
                return ResourceManager.GetString("GetPossibleActionsQuery_NoFlowWasFoundForThisRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to این کاربر مجاز به انجام هیچ عملی در این مرحله نیست.
        /// </summary>
        public static string GetPossibleActionsQuery_ThisUserIsNotAllowedToDoActions {
            get {
                return ResourceManager.GetString("GetPossibleActionsQuery_ThisUserIsNotAllowedToDoActions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to بدلیل عدم تعریف جایگاه شما در سیستم‌ راهکاران (منابع انسانی)، شما مجاز به انجام عملی در این مرحله نمی‌باشید.
        /// </summary>
        public static string GetPossibleActionsQuery_YouHaveNoBoxSoCantHaveAction {
            get {
                return ResourceManager.GetString("GetPossibleActionsQuery_YouHaveNoBoxSoCantHaveAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ارتباط با سرویس گردش کار برقرار نشد.
        /// </summary>
        public static string SomeErrorHappendInWorkFlow {
            get {
                return ResourceManager.GetString("SomeErrorHappendInWorkFlow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to فرمت فایل معتبر نمی‌باشد.
        /// </summary>
        public static string Uploader_InvalidFileFormat {
            get {
                return ResourceManager.GetString("Uploader_InvalidFileFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to حجم فایل بیشتر از حد مجاز 10 مگابایت می‌باشد.
        /// </summary>
        public static string Uploader_SizeExceeded {
            get {
                return ResourceManager.GetString("Uploader_SizeExceeded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to هیچ تاریخچه‌ای یافت نشد. از درستی شناسه درخواست مطمئن شوید.
        /// </summary>
        public static string Workflow_NoHistoryWasFound {
            get {
                return ResourceManager.GetString("Workflow_NoHistoryWasFound", resourceCulture);
            }
        }
    }
}
